### PR TITLE
Update Rust integration docs

### PR DESCRIPTION
**Pull request by ChrisWhealy**
Multiple change that include:

* Change all occurrences of "wasm" or "Wasm" to "WASM" except where they occur in a file or path name
* Extend the Rust integration examples to provide step by step instructions
* Add a page for preparing guest WASM modules used in the Rust integration examples
* Update screen shots from WAPM website
* Adapted the Rust error-handling example because setting RUST_BACKTRACE=1 no longer produces a stack trace for errors originating outside Rust.  Document a minimal use of `rust-lldb`

(Have not touched the C integration examples except where the capitalisation of "WASM" took place)

### CODE REVIEW

**Comment by syrusakbary** [comment]
Thanks for the contribution @ChrisWhealy!

We just merged a huge refactor into our docs (you can see the new version in https://new-docs.wasmer.io), but I'd love to get your changes there as well.

**Comment by syrusakbary** [comment]
Note: if you want, I can give you access to the Gitbook page. With it you will be able to modify all pages in Gitbook itself with the same UI as the docs website :)

**Comment by ChrisWhealy** [comment]
Yes, I saw you’ve added Gitbook annotations just as I was preparing the PR...
If I’ve oils work direct from the Gitbook UI, that would be helpful - it would also help reduce divergent changes (like this last one)

**Comment by syrusakbary** [comment]
Hi @ChrisWhealy,

You can use this link to register:
https://app.gitbook.com/invite/wasmer?invite=-M0ers_N6QoAwitloG8J

You will have automatically access to the Wasmer Docs Gitbook with write access.

**Comment by jubianchi** [comment]
Hi @ChrisWhealy thanks again for your work here!

We are doing another big change on the documentation (see #76) and most of the changes you suggested were made or are now outdated.

I'm closing this PR as it not relevant any more but thanks again for your work 👍

**Pull request closed without merging**
