### PR TITLE
Add instruction on which dependency is required

### PR DESCRIPTION
**Pull request by marcofranssen**

### CODE REVIEW

**Comment by jubianchi** [comment]
Hi @marcofranssen, thanks a lot for the PRs your are sending but I do not want you to spend too much time on the examples from `master` as we are rewriting them.

Have a look [here](https://github.com/wasmerio/docs.wasmer.io/tree/doc-update-1.0/integrations/examples) to see the new ones. Feedback welcome 🙂

Thanks for your work here, it's really appreciated!

**Comment by marcofranssen** [comment]
Thanks for the heads-up. Is it already viewable in some kind of prerelease deployment? That would make it easier to digest.

**Comment by marcofranssen** [comment]
@jubianchi I would be more then happy to provide feedback. Maybe open a Draft PR so I can give you some feedback already.

**Comment by jubianchi** [comment]
> Thanks for the heads-up. Is it already viewable in some kind of prerelease deployment? That would make it easier to digest.

@marcofranssen you can see it live here: https://jubianchi.gitbook.io/wasmer-docs/v/doc-update-1.0/

**Comment by marcofranssen** [comment]
@jubianchi thanks for sharing that url.

I do have some feedback for you which would be most convenient to give directly in a PR.

**Comment by jubianchi** [comment]
@marcofranssen here you go: https://github.com/wasmerio/docs.wasmer.io/pull/79 😉

**Comment by marcofranssen** [comment]
Will continue the discussion on the new PR #79

**Pull request closed without merging**
